# NumPy Library
---

Numpy is the core library for scientific computing in Python. It provides a high performance multidimensional array object and tools for working with these arrays. If you are familiar with MATLAB, you light find this tutorial useful to get started with Numpy.

Numpy is much more efficient than using lists as a data type and performing operations on those lists. It is mostly used for dealing with arrays and mathematical computations on matrices and operations on those matrices such as transpose, dot product, cross product, etc.

W3Schools: https://www.w3schools.com/python/numpy/numpy_creating_arrays.asp

GitHub Link: https://github.com/numpy/numpy

To use Numpy, we first need to import the numpy package:

In [17]:
# import Numpy package and refer to it as "np"

import numpy as np

## Arrays: The Basics
---

A Numpy array is a grid of values and they have the same data type. 
Python array indices always start at [0]

In [18]:
# Numpy can create arrays of different rank (aka dimension)
# access command: ndim (number of dimensions)

a = np.array([1, 2, 3])   # This is an array of rank 1 (single dimension)

# check for the type that is created by numpy
print(f'Type of Numpy array is {type(a)}')

# check for the shape that we created
print(f'Shape of array: {a.shape}')

# print the individual elements in array 'a'
print(f'1st Element is: {a[0]}\n2nd Element is: {a[1]}\n3rd Element is: {a[2]}')

Type of Numpy array is <class 'numpy.ndarray'>
Shape of array: (3,)
1st Element is: 1
2nd Element is: 2
3rd Element is: 3


In [19]:
print(a)

a

[1 2 3]


array([1, 2, 3])

In [20]:
# Create an array of rank 2

b = np.array([[1,2,3],[4,5,6]])   # this is a 2 dimensional matrix array

print(f'Type of Numpy array is {type(b)}')

# check for the shape that we created

print(f'Shape of array: {b.shape}')

# print the individual elements in array 'b'

print(f'Elements in the 1st row of b:\n1st Element is: {b[0,0]}\n2nd Element is: {b[0,1]}\n3rd Element is: {b[0,2]}')
print(f'Elements in the 2nd row of b:\n1st Element is: {b[1,0]}\n2nd Element is: {b[1,1]}\n3rd Element is: {b[1,2]}')

Type of Numpy array is <class 'numpy.ndarray'>
Shape of array: (2, 3)
Elements in the 1st row of b:
1st Element is: 1
2nd Element is: 2
3rd Element is: 3
Elements in the 2nd row of b:
1st Element is: 4
2nd Element is: 5
3rd Element is: 6


In [21]:
print(b)

b

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# Create an array of zeros:
z = np.zeros((2,2))   # 2x2 matrix filled with zeros
print(z, '\n')

# Create an array of ones:
o = np.ones((2,2))    # 2x2 matrix filled with ones
print(o, '\n')

# Create an array of some specific value:
f = np.full((2,2),5)    # 2x2 matrix, specific value is 5
print(f, '\n')

# Create an identity matrix
e = np.eye(5)   # creates a 5x5 identity matrix
print(e, '\n')

# Create an array of random values
r = np.random.random((4,4))   # creates a 4x4 shaped random value matrix
print(r, '\n')

[[0. 0.]
 [0. 0.]] 

[[1. 1.]
 [1. 1.]] 

[[5 5]
 [5 5]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[[0.98910998 0.34776754 0.73904182 0.28784816]
 [0.76490857 0.10753245 0.19478799 0.26652742]
 [0.27268694 0.6436167  0.947759   0.87492761]
 [0.29138652 0.48385749 0.48697123 0.40103061]] 



## Array Indexing
---
How to create matrix arrays and copy them.

In [23]:
# Create a 3x4 array

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f'Array a:\n\n{a}\n\nShape of Array: {a.shape}')

Array a:

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape of Array: (3, 4)


In [36]:
# now what if we want to extract 2, 3, 6 and 7 from 'a', and put them in a new array 'b'?
# this is called "slicing" an array:
# we are looking to extract elements from Row 0 and 1, and Column 1 and 2 (remember index starts at 0)

b = a[:2,1:3]   # Syntax [start row : end row, start column : end column] **Leaving the start row empty defaults to Row 0

# note that start row is INCLUDED, but end row is EXCLUDED in the results
print(f'Sliced Array:\n\n{b}\n\nShape of B: {b.shape}')

Sliced Array:

[[13  3]
 [ 6  7]]

Shape of B: (2, 2)


In [25]:
# if we change a value in array 'b', then we change the value in 'a' as well.

b[0,0] = 13 # b[0,0] = a[0,1]
print(f'Array b:\n\n{b}\n\nArray a:\n\n{a}')

Array b:

[[13  3]
 [ 6  7]]

Array a:

[[ 1 13  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
# to avoid this we need to create a "copy" instead...

c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f'Array c:\n\n{c}\n\nShape of Array: {c.shape}')

Array c:

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape of Array: (3, 4)


In [27]:
# now we'll slice array 'c' just like we did previously, but by making a copy instead

d = c[:2,1:3].copy()    # we copied array c before slicing it, so we can change either one without affecting the other
print(f'Sliced Array:\n\n{d}\n\nShape of d: {d.shape}')

Sliced Array:

[[2 3]
 [6 7]]

Shape of d: (2, 2)


In [28]:
d[0,0] = 13
print(f'Array d:\n\n{d}\n\nArray c:\n\n{c}')

# note that d changed but c did not in this case

Array d:

[[13  3]
 [ 6  7]]

Array c:

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
# Choosing specific datatypes for arrays:
x = np.array([1,2])   # data type "int64: chosen by numpy since we entered integers
y = np.array([1.0, 2.0])    # data type "float64" chosen by numpy since we entered in decimals
z = np.array([1,2], dtype = np.float64)   # user specified data type as float64 even though we entered integers

print(x.dtype, y.dtype, z.dtype)
print(f'Array x data type: {x.dtype}\nArray y data type: {y.dtype}\nArray z data type: {z.dtype}')

int64 float64 float64
Array x data type: int64
Array y data type: float64
Array z data type: float64


## Array Math
---
The strength of Numpy...

In [30]:
# Addition & Subtraction of arrays:

x = np.array(([1,2],[3,4]))
y = np.array(([5,6],[7,8]))

# Elementwise sum
z = x + y
w = x - y

print('2 ways to add & subtract matrices:\n')
print(z, '\n')
print(w, '\n')
print(np.add(x,y), '\n')
print(np.subtract(x,y))

2 ways to add & subtract matrices:

[[ 6  8]
 [10 12]] 

[[-4 -4]
 [-4 -4]] 

[[ 6  8]
 [10 12]] 

[[-4 -4]
 [-4 -4]]


In [31]:
# Multiplication and Division

zz = x * y    
ww = x / y

print('2 ways to multiply & divide matrices:\n')
print(zz, '\n')
print(ww, '\n')
print(np.multiply(x,y), '\n')
print(np.divide(x,y))

2 ways to multiply & divide matrices:

[[ 5 12]
 [21 32]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]] 

[[ 5 12]
 [21 32]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [32]:
# Square Root of matrix x
print(f'Matrix x:\n\n{x}\n')
aa = np.sqrt(x)
print(f'Matrix sqrt(x):\n\n{aa}\n')
print(f'Matrix sqrt(x):\n\n{np.sqrt(x)}\n')

# Square Root of marix zz
bb = np.sqrt(zz)
print(f'Matrix zz:\n\n{zz}\n')
print(f'Matrix sqrt(zz):\n\n{np.sqrt(zz)}\n\n')
print(f'Matrix sqrt(zz):\n\n{bb}')

Matrix x:

[[1 2]
 [3 4]]

Matrix sqrt(x):

[[1.         1.41421356]
 [1.73205081 2.        ]]

Matrix sqrt(x):

[[1.         1.41421356]
 [1.73205081 2.        ]]

Matrix zz:

[[ 5 12]
 [21 32]]

Matrix sqrt(zz):

[[2.23606798 3.46410162]
 [4.58257569 5.65685425]]


Matrix sqrt(zz):

[[2.23606798 3.46410162]
 [4.58257569 5.65685425]]


In [33]:
# Dot Product of matrices x and y

print(f'x:\n\n{x}\n')
print(f'y:\n\n{y}\n')

print(f'zz = x * y:\n\n{zz}\n')    
print(zz)

print(f'\nDot Product of X and Y:\n')
print(f'{x.dot(y)}\n')
print(np.dot(x,y))

x:

[[1 2]
 [3 4]]

y:

[[5 6]
 [7 8]]

zz = x * y:

[[ 5 12]
 [21 32]]

[[ 5 12]
 [21 32]]

Dot Product of X and Y:

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


In [34]:
# Take sum of the contents of array a:
print(f'Array x:\n\n{x}')
print(f'\nSum of Array x:\n\n{np.sum(x)}')
print(f'\nSum of Array x, Axis 0:\n\n{np.sum(x, axis = 0)}')
print(f'\nSum of Array x, Axis 1:\n\n{np.sum(x, axis = 1)}')

Array x:

[[1 2]
 [3 4]]

Sum of Array x:

10

Sum of Array x, Axis 0:

[4 6]

Sum of Array x, Axis 1:

[3 7]


In [35]:
# Transpose of a Matrix:
# Switch the rows with the columns

# view your window in the transpose window
# useful for linear regession, logistical regression algorithms when you need to multiply matrices by their transpose

print(f'Matrix x:\n\n{x}\n')
print(f'Matrix x.T:\n\n{x.T}\n')

Matrix x:

[[1 2]
 [3 4]]

Matrix x.T:

[[1 3]
 [2 4]]

